env:
  - BASE=centos

sudo: required
services:
  - docker

before_install:
  # Docker Repository
  - export REPO=fjudith/sybase
  # Compute docker tag
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - export VERSION=`cat VERSION`

script:
  - set -e
  - docker build -f ${BASE}/Dockerfile -t ${REPO}:${VERSION} {BASE}/
  - docker run -d --name localhost -p 5000:5000 ${REPO}:${VERSION}
  - chmod +x ./test/docker_image.sh
  - ./test/docker_image.sh
after_success: >-
  set -e
  if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then
    echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin &&
    docker tag ${REPO}:${VERSION} ${REPO}:${TAG} &&
    docker push ${REPO}:{TAG}
  fi
