env:
  - BASE=centos
  # Docker Repository
  - REPO=fjudith/sybase
  # Compute docker tag
  - TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`


sudo: required
services:
  - docker

before_install:
  - export VERSION=`cat VERSION`

script: >-
  set -e
  cd ${BASE}/
  docker build -t ${REPO}:{VERSION} .
  docker run -d --name sybase -p 5000:5000 ${REPO}:{VERSION}
  sleep 30
  docker logs sybase
  docker exec -it sysbase isql -Usa -PmyPassword -SMYSYBASE
after_success: >-
  set -e
  if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then
    echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin &&
    docker tag ${REPO}:${VERSION} ${REPO}:${TAG}
    docker push ${REPO}:{TAG}
  fi
