name: Ansible / FreeTDS

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 
      
      - name: Build & Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: docker.io/fjudith/sybase:${{ env.GITHUB_REF_NAME }}-ansible
          context: ./ansible/
          file: ./ansible/Dockerfile
          platforms: linux/amd64
          push: True
