name: Ansible-Test with SAP OpenClient

on:
 push:
  paths:
    - 'ansible-test/**'
    - 'sap-ocs/**'
    - 'test/**'
    - '.github/workflows/ansible_test_client.yaml'
  pull_request:
    paths:
    - 'ansible-test/**'
    - 'sap-ocs/**'
    - 'test/**'
    - '.github/workflows/ansible-test_client.yaml'

env:
  REPOSITORY: "docker.io/sqlops/sybase-test-container"
  DOCKERFILE: "ansible-test/Dockerfile.ci"
  ENF_FILE: "./ansible-test/.env"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      
      - name: Set ENV variables
        run: |
          cat ${{ env.ENV_FILE }} >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 

      - name: Build image
        run: |
          docker image build -f ${{ env.DOCKERFILE }} \
          --tag ${{ env.REPOSITORY}}:${{ env.SEMVER_MAJOR }} \
          --tag ${{ env.REPOSITORY}}:${{ env.SEMVER_MINOR }} \
          --tag ${{ env.REPOSITORY}}:${{ env.SEMVER_PATCH }} \
          --tag ${{ env.REPOSITORY}}:${{ env.SEMVER_TAG }} \
          --tag ${{ env.REPOSITORY}}:latest \
          ./

      - name: Push image
        id: docker_push
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.REPOSITORY}}
          context: ./
          file: ${{ env.DOCKERFILE }}
          platforms: linux/amd64
          push: True