name: Ansible PyODBC

on:
 push:
  paths:
    - 'ansible/**'
    - 'test/**'
    - '.github/workflows/ansible_client.yaml'
  pull_request:
    paths:
    - 'ansible/**'
    - 'test/**'
    - '.github/workflows/ansible_client.yaml'

env:
  IMAGE: "docker.io/sqlops/ansible-pyodbc"
  DOCKERFILE: "./ansible/Dockerfile"
  ENV_FILE: "./ansible/.env"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      
      - name: Set ENV variables
        run: |
          cat ${{ env.ENV_FILE }} >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 

      - name: Build image
        run: |
          docker image build -f ${{ env.DOCKERFILE }} \
          --tag ${{ env.IMAGE}}:${{ env.SEMVER_MAJOR }} \
          --tag ${{ env.IMAGE}}:${{ env.SEMVER_MINOR }} \
          --tag ${{ env.IMAGE}}:${{ env.SEMVER_PATCH }} \
          --tag ${{ env.IMAGE}}:${{ env.SEMVER_TAG }} \
          --tag ${{ env.IMAGE}}:latest \
          ./

      - name: Push images
        run: |
          docker image push ${{ env.IMAGE}}:${{ env.SEMVER_MAJOR }} && \
          docker image push ${{ env.IMAGE}}:${{ env.SEMVER_MINOR }} && \
          docker image push ${{ env.IMAGE}}:${{ env.SEMVER_PATCH }} && \
          docker image push ${{ env.IMAGE}}:${{ env.SEMVER_TAG }} && \
          docker image push ${{ env.IMAGE}}:latest
