name: Docker CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: docker.io/fjudith/sybase:${{ env.GITHUB_REF_NAME }}
          context: ./centos/
          file: ./centos/Dockerfile
          platforms: linux/amd64
          push: true
      
      - name: Test
        run: |
          docker run -d --name sybase -p 5000:5000 fjudith/sybase:${{ env.GITHUB_REF_NAME }}

          echo "Wait for Sysbase initialization"
          until nc -vz sybase 5000 > /dev/null 2>1; do printf '.' && sleep 5; done
          echo " "

          until docker container logs sybase | grep "SYBASE INITIALIZED" > /dev/null 2>1; do printf '.' && sleep 1; done

          alias isql="docker exec -it sysbase isql -Usa -PmyPassword -SMYSYBASE -d "master"
          cat << EOF | isql
          select name,id from sysobjects
          go
          EOF
