name: Docker CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 
      
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: docker.io/fjudith/sybase:${{ env.GITHUB_REF_NAME }}
          context: ./centos/
          file: ./centos/Dockerfile
          platforms: linux/amd64
          load: true
      
      - name: Test Shell
        run: |
          ls -lha
          docker run -d --name sybase \
          -v "$(pwd)/test/dataset:/var/lib/dataset" \
          -p 5000:5000 \
          docker.io/fjudith/sybase:${{ env.GITHUB_REF_NAME }}
          chmod +x ./test/docker_image.sh
          ./test/docker_image.sh

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'

      - name: Test Python
        run: |
          docker ps -a
          chmod +x ./test/import_fakenames.sh
          ./test/import_fakenames.sh

      - name: Push
        id: docker_push
        uses: docker/build-push-action@v2
        with:
          tags: docker.io/fjudith/sybase:${{ env.GITHUB_REF_NAME }}
          context: ./centos/
          file: ./centos/Dockerfile
          platforms: linux/amd64
          push: true
