name: Docker CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: docker.io/fjudith/sybase:${{ env.GITHUB_REF_NAME }}
          context: ./centos/
          file: ./centos/Dockerfile
          platforms: linux/amd64
          push: true
      
      - name: Test
        uses: actions/checkout@v2
        run: |
          docker run -d --name sybase -p 5000:5000 docker.io/fjudith/sybase:${{ env.GITHUB_REF_NAME }}
          chmod +x ./test/docker_test.sh
          ./test/docker_test.sh
